import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import { Button } from "baseui/button";
import { styled } from "baseui";
import { Nav } from "@/components/nav";
import { HeadingMedium } from "baseui/typography";
import { MapSelector } from "@/components/map-selector";
const AppContainer = styled("div", ({ $theme }) => {
  return {
    background: $theme.colors.backgroundPrimary,
    height: "100vh",
    width: "100vw",
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  };
});

const Container = styled("div", ({ $theme }) => ({
  maxWidth: "1000px",
  flex: 1,
  display: "inline-flex",
  flexDirection: "column",
  gap: "64px",
  padding: "32px 16px",
  width: "100%",
  overflowY: "auto",
}));

export default function Home() {
  const [bounds, setBounds] = useState({
    ne: { lng: 0, lat: 0 },
    sw: { lng: 0, lat: 0 },
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppContainer>
        <Nav />
        <Container>
          <HeadingMedium margin="0">
            Create a 3D Printed Terrain Map
          </HeadingMedium>
          <MapSelector bounds={bounds} setBounds={setBounds} />
          <Button>Generate 3D Map</Button>
        </Container>
      </AppContainer>
    </>
  );
}
